### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'is_active'

### ISSUE THREAD

**Issue by nawazxy** [ministryofjustice/fab-oidc#8]

**Comment by nawazxy** [comment]
Any suggestions to resolve this error?
<img width="1680" alt="Screen Shot 2020-02-08 at 9 35 15 PM" src="https://user-images.githubusercontent.com/57980436/74089484-04515400-4abb-11ea-9abd-3a396cbb0063.png">

**Comment by NathanDalley** [comment]
Check your database and confirm that the user is present in the table, confirm that the 'active' column is set.

**Comment by NathanDalley** [comment]
this may be related to #4 your user isn't correctly being added to the database and returning a value of false. 
The login_user function is then calling the is_active function on user when its value is _False_ and not a user.
This would result in the error you're getting.

Investigate why your user is not being added correctly to the database.

**Comment by NathanDalley** [comment]
This was happening to me earlier.  I had rebuilt my database from scratch, including users and roles.
I have this value in my config
> AUTH_USER_REGISTRATION_ROLE = "Alpha"

At the time of logging in, the 'Alpha' role did not yet exist, so the add_user failed, resulting in the above error.

**Comment by nawazxy** [comment]
Thanks for the reply Nathan. In my case, the error popped up on user registration and sign in. The entry was being added to the users table correctly with the active status set as well. I was able to resolve this error by simply running the following commands:
- **superset db upgrade**
- **superset init**
